[mypy]
python_version = 3.12
strict = true
show_error_codes = true
pretty = true
mypy_path = guardian
follow_imports = silent
warn_unused_configs = true

[mypy-verify_run]
ignore_errors = true

[mypy-verify_run_v2]
ignore_errors = true
